deploy:
- type: git
  repo: 
    gitee: https://gitee.com/ndgchain/ndgchain.gitee.io.git
    github: https://github.com/ndgchain/ndgchain.github.io.git
  branch: master

<!-- cdn.jsdelivr.net/gh/你的用户名/你的仓库名@发布的版本号/文件路径 -->
<!-- https://cdn.jsdelivr.net/gh/TRHX/CDN-for-itrhx.com@1.0/images/trhx.png -->
<!-- https://cdn.jsdelivr.net/gh/ndgchain/ndgchain.github.io/image/1.png -->

# https://cdn.jsdelivr.net/gh/ndgchain/ndgchain.github.io/dapp/ndgchain-ver1.apk